language: node_js
node_js:
  - 8
install: 
  - npm install
script:
  - npm run build
branches:
  only:
  - master
  - stable
addons:
  ssh_known_hosts:
  - 144.48.141.179
  - yifan.moe
before_install:
  - cat ~/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_2749aaa3c5b2_key -iv $encrypted_2749aaa3c5b2_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  # - scp -o StrictHostKeyChecking=no ./ root@$serverhost:$serverpath
after_success:
  - ls -al
  - scp -o StrictHostKeyChecking=no -r build root@$serverhost:$serverpath